---
- name: create provisioning network definition
  template: src=provisioning.xml.j2 dest=/tmp/provisioning.xml

- name: start provisioning network
  shell: >
    virsh net-define /tmp/provisioning.xml;
    virsh net-autostart provisioning;
    virsh net-start provisioning
  register: provisioning_network
  failed_when: provisioning_network.stderr != '' and 'network is already active' not in provisioning_network.stderr
