---
- name: install internal repos
  yum: name=http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm state=present

- name: install Red Hat Director rpm
  command: rhos-release -p {{ director_repo }}
  
- name: install Red Hat OSP rpm
  command: rhos-release -p {{ osp_repo }}

- name: enable nested virt
  template: src=kvm_intel.conf.j2 dest=/etc/modprobe.d/kvm_intel.conf

- name: disable rp_filter
  template: src=98-rp-filter.conf.j2 dest=/etc/sysctl.d/98-rp-filter.conf

- name: upgrade packages
  yum: name=* state=latest
  when: ({{ no_pkg_update }} == false)

- name: install pip
  command: easy_install pip

- name: reboot
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: ({{ post_haste }} == false and {{ no_pkg_update }} == false)
